# Generated by Django 2.0.4 on 2018-05-31 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='clientAuthdeatils',
        ),
    ]
